sudo: required
services:
    - docker

before_install:
    - docker build -t hrugved/react-test -f ./client/Dockerfile.dev ./client

script: 
    - docker run -e CI=true hrugved/react-test npm test
    
after_success:
    - docker build -t hrugved/fib-multi-client ./client
    - docker build -t hrugved/fib-multi-nginx ./nginx
    - docker build -t hrugved/fib-multi-server ./server
    - docker build -t hrugved/fib-multi-worker ./worker
    # login to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # take those images and push them to docker hub
    - docker push hrugved/fib-multi-client
    - docker push hrugved/fib-multi-nginx
    - docker push hrugved/fib-multi-server
    - docker push hrugved/fib-multi-worker

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: fib-multi
    env: FibMulti-env
    bucket_name: elasticbeanstalk-us-east-2-166632679605
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: 
        secure: $AWS_SECRET_KEY



