version: '3'
services: 
    postgres:
        image: 'postgres:latest'
    redis:
        image: 'redis:latest'
    nginx:
        restart: always
        build:
            context: ./nginx
            dockerfile: Dockerfile.dev
        ports:
            - 4000:80
    api:
        build:
            context: ./server
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - ./server:/app
        environment: 
            - REDIS_HOST=redis #just specify the name of service
            - REDIS_PORT=6379 #redis official docs
            - PGUSER=postgres #default
            - PGHOST=postgres #name of service
            - PGDATABASE=postgres #default
            - PGPASSWORD=postgres_password #default
            - PGPORT=5432 #offical docs
        depends_on:
            - postgres
    client:
        build:
            context: ./client
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - ./client:/app
    worker:
        build:
            context: ./worker
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - ./worker:/app
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379